version: 2.1

.cache_archive_steps: &cache_archive_steps
  - checkout

  - run:
      name: download and extract package
      command: |
        wget -O package.tar.gz https://github.com/NixOS/nixpkgs/archive/refs/tags/23.11.tar.gz
        mkdir package
        tar xf package.tar.gz -C package

  - save_cache:
      key: package-<< parameters.executor >>-<< parameters.resource_class >>-{{ .Environment.CIRCLE_SHA1 }}
      paths:
        - package

.cache_extract_steps: &cache_extract_steps
  - checkout

  - restore_cache:
      keys:
        - package-<< parameters.executor >>-<< parameters.resource_class >>-{{ .Environment.CIRCLE_SHA1 }}

  - run:
      name: check exists
      command: |
        ls -al
        test -d package

jobs:
  cache_archive_linux_docker:
    parameters:
      resource_class:
        type: string
      executor:
        type: string
    docker:
      - image: busybox:latest
    resource_class: "<< parameters.resource_class >>"
    steps: *cache_archive_steps

  cache_extract_linux_docker:
    parameters:
      resource_class:
        type: string
      executor:
        type: string
    docker:
      - image: busybox:latest
    resource_class: "<< parameters.resource_class >>"
    steps: *cache_extract_steps

  cache_archive_linux_machine:
    parameters:
      resource_class:
        type: string
      executor:
        type: string
    machine:
      image: ubuntu-2204:2022.10.2
    resource_class: "<< parameters.resource_class >>"
    steps: *cache_archive_steps

  cache_extract_linux_machine:
    parameters:
      resource_class:
        type: string
      executor:
        type: string
    machine:
      image: ubuntu-2204:2022.10.2
    resource_class: "<< parameters.resource_class >>"
    steps: *cache_extract_steps

  cache_archive_windows_machine:
    parameters:
      resource_class:
        type: string
      executor:
        type: string
    machine:
      image: windows-server-2022-gui:current
      shell: powershell.exe -ExecutionPolicy Bypass
    resource_class: "<< parameters.resource_class >>"
    steps:
      - checkout

      - run:
          name: download and extract package
          command: |
            $ProgressPreference = 'SilentlyContinue'
            Invoke-WebRequest 'https://github.com/NixOS/nixpkgs/archive/refs/tags/23.11.tar.gz' -OutFile package.tar.gz
            mkdir package
            tar xf package.tar.gz -C package

      - save_cache:
          key: package-<< parameters.executor >>-<< parameters.resource_class >>-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - package

  cache_extract_windows_machine:
    parameters:
      resource_class:
        type: string
      executor:
        type: string
    machine:
      image: windows-server-2022-gui:current
    resource_class: "<< parameters.resource_class >>"
    steps: *cache_extract_steps

  cache_archive_macos:
    parameters:
      resource_class:
        type: string
      executor:
        type: string
    macos:
      xcode: 14.2.0
    resource_class: "<< parameters.resource_class >>"
    steps: *cache_archive_steps

  cache_extract_macos:
    parameters:
      resource_class:
        type: string
      executor:
        type: string
    macos:
      xcode: 14.2.0
    resource_class: "<< parameters.resource_class >>"
    steps: *cache_extract_steps

workflows:
  version: 2
  build_and_cache:
    jobs:
      - cache_archive_linux_docker:
          matrix:
            parameters:
              resource_class: ["small", "medium", "medium+", "large", "arm.medium", "arm.large"]
              executor: ["docker"]
      - cache_extract_linux_docker:
          matrix:
            parameters:
              resource_class: ["small", "medium", "medium+", "large", "arm.medium", "arm.large"]
              executor: ["docker"]
          requires:
            - cache_archive_linux_docker

      - cache_archive_linux_machine:
          matrix:
            parameters:
              resource_class: ["medium", "large", "arm.medium", "arm.large"]
              executor: ["machine"]

      - cache_extract_linux_machine:
          matrix:
            parameters:
              resource_class: ["medium", "large", "arm.medium", "arm.large"]
              executor: ["machine"]
          requires:
            - cache_archive_linux_machine

      - cache_archive_windows_machine:
          matrix:
            parameters:
              resource_class: ["windows.medium", "windows.large"]
              executor: ["machine"]

      - cache_extract_windows_machine:
          matrix:
            parameters:
              resource_class: ["windows.medium", "windows.large"]
              executor: ["machine"]
          requires:
            - cache_archive_windows_machine

      - cache_archive_macos:
          matrix:
            parameters:
              resource_class: ["macos.x86.medium.gen2"]
              executor: ["macos"]

      - cache_extract_macos:
          matrix:
            parameters:
              resource_class: ["macos.x86.medium.gen2"]
              executor: ["macos"]
          requires:
            - cache_archive_macos
